name: Build & Deploy Myapp
#Triggers : when ? 
on: 
  push:
    branches:
      - main 

#Jobs
#Run : machine ?
#Step = Action
jobs:
  build-deploy:
    name: Build And Deploy MyApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
