name: Build & Deploy Myapp

on: 
  push:
    branches:
      - main 

jobs:
  build-deploy:
    name: Build And Deploy MyApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testpipeline:v1

      - name: Login to Docker Hub 
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testpipeline:v1

      - name: Login to ArgoCD
        run: |
          argocd login localhost:33945 --username admin --password Mouhamed2000** --insecure
      - name: Sync ArgoCD Application
        run: |
          argocd app sync helm-app-using-terraform  # Remplacez helm-app-using-terraform par le nom de votre application ArgoCD
          argocd app wait helm-app-using-terraform
